#!/bin/bash
	postfix=81
	for ip in $( cat /appserver/crontabjobs/serverip/testserversip)
	do
		echo $ip
		#ssh $ip "sysctl kernel.hostname='rfhtest$postfix'"
		ssh $ip "sed -i 's/$ip/$ip rfhtest$postfix/g'" /etc/hosts
		postfix=$(($postfix + 1))
		echo $postfix
	done
